app:
    resource: "@AppBundle/Controller/"
    type: annotation
    prefix: /api

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc
#app_links:
#    type: rest
#    prefix: /api
#    resource: "@AppBundle/Resources/config/routes.yml"