home:
    resource: "@AppBundle/Controller/HomeController.php"
    type: annotation

links:
    resource: "@AppBundle/Controller/LinksController.php"
    type: annotation
    prefix: /api

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

redirect:
    resource: "@AppBundle/Controller/RedirectController.php"
    type: annotation